package pojo;
// Generated 03-Sep-2019 12:32:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Answers generated by hbm2java
 */
public class Answers  implements java.io.Serializable {


     private Integer idAnswers;
     private Question question;
     private String text;
     private Byte iscorrect;
     private Set answersHistories = new HashSet(0);

    public Answers() {
    }

	
    public Answers(Question question) {
        this.question = question;
    }
    public Answers(Question question, String text, Byte iscorrect, Set answersHistories) {
       this.question = question;
       this.text = text;
       this.iscorrect = iscorrect;
       this.answersHistories = answersHistories;
    }
   
    public Integer getIdAnswers() {
        return this.idAnswers;
    }
    
    public void setIdAnswers(Integer idAnswers) {
        this.idAnswers = idAnswers;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Byte getIscorrect() {
        return this.iscorrect;
    }
    
    public void setIscorrect(Byte iscorrect) {
        this.iscorrect = iscorrect;
    }
    public Set getAnswersHistories() {
        return this.answersHistories;
    }
    
    public void setAnswersHistories(Set answersHistories) {
        this.answersHistories = answersHistories;
    }




}


