package pojo;
// Generated 03-Sep-2019 12:32:22 by Hibernate Tools 4.3.1



/**
 * AnswersHistory generated by hbm2java
 */
public class AnswersHistory  implements java.io.Serializable {


     private Integer idAnswersHistory;
     private Answers answers;
     private PracticeQuestionSet practiceQuestionSet;
     private QuestionSet questionSet;
     private User user;
     private String answer;
     private String type;

    public AnswersHistory() {
    }

    public AnswersHistory(Answers answers, PracticeQuestionSet practiceQuestionSet, QuestionSet questionSet, User user, String answer, String type) {
       this.answers = answers;
       this.practiceQuestionSet = practiceQuestionSet;
       this.questionSet = questionSet;
       this.user = user;
       this.answer = answer;
       this.type = type;
    }
   
    public Integer getIdAnswersHistory() {
        return this.idAnswersHistory;
    }
    
    public void setIdAnswersHistory(Integer idAnswersHistory) {
        this.idAnswersHistory = idAnswersHistory;
    }
    public Answers getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Answers answers) {
        this.answers = answers;
    }
    public PracticeQuestionSet getPracticeQuestionSet() {
        return this.practiceQuestionSet;
    }
    
    public void setPracticeQuestionSet(PracticeQuestionSet practiceQuestionSet) {
        this.practiceQuestionSet = practiceQuestionSet;
    }
    public QuestionSet getQuestionSet() {
        return this.questionSet;
    }
    
    public void setQuestionSet(QuestionSet questionSet) {
        this.questionSet = questionSet;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


