package pojo;
// Generated 03-Sep-2019 12:32:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EnumSecurityQuestions generated by hbm2java
 */
public class EnumSecurityQuestions  implements java.io.Serializable {


     private Integer idsecquestion;
     private String question;
     private Integer isactive;
     private Set users = new HashSet(0);

    public EnumSecurityQuestions() {
    }

	
    public EnumSecurityQuestions(String question) {
        this.question = question;
    }
    public EnumSecurityQuestions(String question, Integer isactive, Set users) {
       this.question = question;
       this.isactive = isactive;
       this.users = users;
    }
   
    public Integer getIdsecquestion() {
        return this.idsecquestion;
    }
    
    public void setIdsecquestion(Integer idsecquestion) {
        this.idsecquestion = idsecquestion;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public Integer getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


