package pojo;
// Generated 03-Sep-2019 12:32:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EnumQuestionSetStatus generated by hbm2java
 */
public class EnumQuestionSetStatus  implements java.io.Serializable {


     private Integer idqestionsetstatus;
     private String status;
     private Set questionSets = new HashSet(0);

    public EnumQuestionSetStatus() {
    }

    public EnumQuestionSetStatus(String status, Set questionSets) {
       this.status = status;
       this.questionSets = questionSets;
    }
   
    public Integer getIdqestionsetstatus() {
        return this.idqestionsetstatus;
    }
    
    public void setIdqestionsetstatus(Integer idqestionsetstatus) {
        this.idqestionsetstatus = idqestionsetstatus;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getQuestionSets() {
        return this.questionSets;
    }
    
    public void setQuestionSets(Set questionSets) {
        this.questionSets = questionSets;
    }




}


