package pojo;
// Generated 03-Sep-2019 12:32:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PracticeQuestionSet generated by hbm2java
 */
public class PracticeQuestionSet  implements java.io.Serializable {


     private Integer idpracticeQuestionHistory;
     private Question question;
     private User user;
     private Integer score;
     private Date insertTs;
     private Set answersHistories = new HashSet(0);

    public PracticeQuestionSet() {
    }

	
    public PracticeQuestionSet(Question question, User user) {
        this.question = question;
        this.user = user;
    }
    public PracticeQuestionSet(Question question, User user, Integer score, Date insertTs, Set answersHistories) {
       this.question = question;
       this.user = user;
       this.score = score;
       this.insertTs = insertTs;
       this.answersHistories = answersHistories;
    }
   
    public Integer getIdpracticeQuestionHistory() {
        return this.idpracticeQuestionHistory;
    }
    
    public void setIdpracticeQuestionHistory(Integer idpracticeQuestionHistory) {
        this.idpracticeQuestionHistory = idpracticeQuestionHistory;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }
    public Date getInsertTs() {
        return this.insertTs;
    }
    
    public void setInsertTs(Date insertTs) {
        this.insertTs = insertTs;
    }
    public Set getAnswersHistories() {
        return this.answersHistories;
    }
    
    public void setAnswersHistories(Set answersHistories) {
        this.answersHistories = answersHistories;
    }




}


