package pojo;
// Generated 03-Sep-2019 12:32:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * QuestionSet generated by hbm2java
 */
public class QuestionSet  implements java.io.Serializable {


     private Integer idquestionset;
     private EnumQuestionSetStatus enumQuestionSetStatus;
     private EnumSubject enumSubject;
     private User user;
     private String name;
     private Date initiateddate;
     private Set answersHistories = new HashSet(0);
     private Set questions = new HashSet(0);

    public QuestionSet() {
    }

	
    public QuestionSet(EnumQuestionSetStatus enumQuestionSetStatus, EnumSubject enumSubject, User user) {
        this.enumQuestionSetStatus = enumQuestionSetStatus;
        this.enumSubject = enumSubject;
        this.user = user;
    }
    public QuestionSet(EnumQuestionSetStatus enumQuestionSetStatus, EnumSubject enumSubject, User user, String name, Date initiateddate, Set answersHistories, Set questions) {
       this.enumQuestionSetStatus = enumQuestionSetStatus;
       this.enumSubject = enumSubject;
       this.user = user;
       this.name = name;
       this.initiateddate = initiateddate;
       this.answersHistories = answersHistories;
       this.questions = questions;
    }
   
    public Integer getIdquestionset() {
        return this.idquestionset;
    }
    
    public void setIdquestionset(Integer idquestionset) {
        this.idquestionset = idquestionset;
    }
    public EnumQuestionSetStatus getEnumQuestionSetStatus() {
        return this.enumQuestionSetStatus;
    }
    
    public void setEnumQuestionSetStatus(EnumQuestionSetStatus enumQuestionSetStatus) {
        this.enumQuestionSetStatus = enumQuestionSetStatus;
    }
    public EnumSubject getEnumSubject() {
        return this.enumSubject;
    }
    
    public void setEnumSubject(EnumSubject enumSubject) {
        this.enumSubject = enumSubject;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getInitiateddate() {
        return this.initiateddate;
    }
    
    public void setInitiateddate(Date initiateddate) {
        this.initiateddate = initiateddate;
    }
    public Set getAnswersHistories() {
        return this.answersHistories;
    }
    
    public void setAnswersHistories(Set answersHistories) {
        this.answersHistories = answersHistories;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


