package pojo;
// Generated 03-Sep-2019 12:32:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer idquestion;
     private EnumQuestionStatus enumQuestionStatus;
     private EnumSections enumSections;
     private QuestionSet questionSet;
     private String questiontext;
     private String imgpath;
     private Set answerses = new HashSet(0);
     private Set practiceQuestionSets = new HashSet(0);

    public Question() {
    }

	
    public Question(EnumQuestionStatus enumQuestionStatus, EnumSections enumSections, QuestionSet questionSet) {
        this.enumQuestionStatus = enumQuestionStatus;
        this.enumSections = enumSections;
        this.questionSet = questionSet;
    }
    public Question(EnumQuestionStatus enumQuestionStatus, EnumSections enumSections, QuestionSet questionSet, String questiontext, String imgpath, Set answerses, Set practiceQuestionSets) {
       this.enumQuestionStatus = enumQuestionStatus;
       this.enumSections = enumSections;
       this.questionSet = questionSet;
       this.questiontext = questiontext;
       this.imgpath = imgpath;
       this.answerses = answerses;
       this.practiceQuestionSets = practiceQuestionSets;
    }
   
    public Integer getIdquestion() {
        return this.idquestion;
    }
    
    public void setIdquestion(Integer idquestion) {
        this.idquestion = idquestion;
    }
    public EnumQuestionStatus getEnumQuestionStatus() {
        return this.enumQuestionStatus;
    }
    
    public void setEnumQuestionStatus(EnumQuestionStatus enumQuestionStatus) {
        this.enumQuestionStatus = enumQuestionStatus;
    }
    public EnumSections getEnumSections() {
        return this.enumSections;
    }
    
    public void setEnumSections(EnumSections enumSections) {
        this.enumSections = enumSections;
    }
    public QuestionSet getQuestionSet() {
        return this.questionSet;
    }
    
    public void setQuestionSet(QuestionSet questionSet) {
        this.questionSet = questionSet;
    }
    public String getQuestiontext() {
        return this.questiontext;
    }
    
    public void setQuestiontext(String questiontext) {
        this.questiontext = questiontext;
    }
    public String getImgpath() {
        return this.imgpath;
    }
    
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath;
    }
    public Set getAnswerses() {
        return this.answerses;
    }
    
    public void setAnswerses(Set answerses) {
        this.answerses = answerses;
    }
    public Set getPracticeQuestionSets() {
        return this.practiceQuestionSets;
    }
    
    public void setPracticeQuestionSets(Set practiceQuestionSets) {
        this.practiceQuestionSets = practiceQuestionSets;
    }




}


